### ISSUE TITLE
Shigella_sonnei is the only merlin_tag with an underscore

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bioinformatics#107]
https://github.com/theiagen/public_health_bioinformatics/blob/7270b4b62e8be3e8c8fc5c46dfe180d93cb9161d/tasks/taxon_id/task_gambit.wdl#L141C21-L141C36

We might want to adjust this for continuity

**Comment by kapsakcj** [comment]
I'll fix this in PR #74 , Thanks for raising the issue
