### ISSUE TITLE
[TheiaCoV] task_ncbi_scrub.wdl CPU and singleton bugs

### ISSUE THREAD

**Issue by andrewjpage** [theiagen/public_health_bioinformatics#127]
This software assumes all CPUs are available on the system for it to use, so it can explode. Explicitly pass in the CPUs to the command.

Additionally there is an edge case for PE reads where you could have one read removed from one direction and not the other, sending everything out of order. Change the code to ensure that the reads are still paired after scrubbing and remove all singletons. Where one read is masked with Ns, instead of being removed, this is still effectively a singleton and both reads should be removed.

**Comment by kapsakcj** [comment]
Would be a good time to upgrade to the latest v2.2.0 of the scrubber: https://github.com/ncbi/sra-human-scrubber/releases/tag/2.2.0

Will also need to push the docker image to our GAR. Here's where v2.2.0 docker image can be found: https://hub.docker.com/r/ncbi/sra-human-scrubber/tags

**Comment by kapsakcj** [comment]
new version of the scrubber was just released to fix a bug with interleaved paired end files: https://github.com/ncbi/sra-human-scrubber/releases/tag/2.2.1
