### ISSUE TITLE
[TheiaProk] add support for Enterobacter_asburiae, Vp, and Vv for NCBI amrfinder task; update default docker

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#129]
Will require and upgrade to the latest and greatest version (and thus docker image), but there is a new species that is supported by amrfinder

TODOs

- [x] update default docker image to GAR-hosted image `us-docker.pkg.dev/general-theiagen/staphb/ncbi-amrfinderplus:3.11.26-2023-11-15.1`
- [ ] update WDL tasks to accommodate new species `Enterobacter_asburiae`, Vibrio parahaemolytics, and Vibrio vulnificus
  - [ ] `amrfinder`
  - [ ]  `gambit`

**Comment by kapsakcj** [comment]
Need to update default docker image one more time, the latest version and db version is amrfinderplus v3.11.26 and db 2023-11-15.1

Docker image needs to be pushed to our GAR.

Need to add support for this new organism, Enterobacter_asburiae, in addition to Vibrio parahaemolyticus and Vibrio vulnificus. Support for these 2 Vibrio species was added  with v3.11.26 and db 2023-11-15.1

**Comment by kapsakcj** [comment]
most up-to-date docker image is: `us-docker.pkg.dev/general-theiagen/staphb/ncbi-amrfinderplus:3.11.26-2023-11-15.1`

**Comment by kapsakcj** [comment]
see above linked duplicate issue for the most up-to-date version of amrfinderplus and it's database (as of today, there may be another version again in the near future)

**Comment by cimendes** [comment]
Most up to date docker just pushed to GAR: `us-docker.pkg.dev/general-theiagen/staphb/ncbi-amrfinderplus:3.12.8-2024-05-02.2`

@michellescribner Maybe it's worth updating the container now with the issues we've been seeing with _Vibrio cholerae_?

**Comment by kapsakcj** [comment]
I have a few useful assemblies and 1 set of reads that will help test this. Terra table w one SRR accession and GenBank accessions (GCAs) is attached. 

[new-amrfinderplus-testing-samples-Vv_Vp_E-asburiae.tsv.txt](https://github.com/user-attachments/files/15991839/new-amrfinderplus-testing-samples-Vv_Vp_E-asburiae.tsv.txt)

I also have the data (FASTQs and FASTAs) in my Terra workspace in the `amrfinderplus_testing_sample` data table here: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/data
