### ISSUE TITLE
explode 💥  sra_fetch workflow

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#139]
Because saying "explode" sounds so much cooler than saying "separate WDL task from WDL workflow"

This is low priority, not urgent.

Might be good to couple with any changes that might be necessary regarding the unintentional downloading of FASTQ files in SRA Lite format (where all Qscores=30)

**Comment by kapsakcj** [comment]
thank you!

I am a little hesitant to set the default `fastq_dl_opts` equal to `"--verbose --provider sra --only-provider"` but that would be the supposed solution. I would like to test this with way more SRR/ERR accessions to see the impacts.

On the plus side: it would restrict the tool to pulling from SRA (instead of ENA) by default which should resolve the accidental downloading SRA Lite formatted-FASTQs (in almost all cases).

On the negative side: it would take a little bit longer to download, though this time difference is probably negligible in the eyes of our users.

Another negative is that if files are only present on ENA (but not on SRA), then the workflow would likely fail. This will likely be rare as it would affect ERR's recently submitted that have not been synced over to SRA.

**Comment by sage-wright** [comment]
Definitely agree about needing more testing before setting it as a default. How often do the two databases sync?

**Comment by kapsakcj** [comment]
great question, I'm not sure. 

It will sometimes take a week or 2 weeks for SRR accessions to be synced over to ENA. Again a relatively rare situation but if someone is trying to download sequences that were very recently submitted and published on SRA, then this issue may occur.
