### ISSUE TITLE
TheiaProk_ONT improvement requests

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bioinformatics#158]
- [x] See read screening problem in issue #157 
- [x] Mean Q score: Different results output to Terra data table and in Nanoplot HTML "mean_qual" result? Nanoplot max quality seems to be above mean quality output to Terra table? Perhaps quality assessment in cg_pipeline isn't working well for Nanopore data? Some samples are also getting unrealistically high Q scores, e.g. >80! Could we output Nanoplot mean Q score to the data table?
- [ ] For some datasets, seems to be poor for calling MLST with Torsten's MLST tool with some data? May depend on input data quality and therefore quality of assembly.  Could we try NanoMLST or krocus which are specifically intended for Nanopore reads?
- [x] Could we output assembly graph file (gfa) produced by Dragonflye for use with Bandage? Helps with interpreting # contigs vs #plasmids

**Comment by emmadoughty** [comment]
It would be great to also run Nanoplot on clean reads to get average quality and length of reads used downstream

**Comment by sage-wright** [comment]
2023-08-22 task assignments:
@cimendes will (1) output the stats from Nanoplot to show a correct mean Q score, (2) show the Nanoplot task some love, and (3) remove the `cg_pipeline` tasks from the workflow.
@sage-wright will (1) add Dragonflye gfa output and (2) fix the read screening problem.

MLST will require a longer turn-around time and we will revisit another time. Krocus will require a database update, and while NanoMLST has a docker image, we do not have any experience with that task.

**Comment by sage-wright** [comment]
Closed by #164
