### ISSUE TITLE
Cannot coerce snippy_variants_none String to File

### ISSUE THREAD

**Issue by michellescribner** [theiagen/public_health_bioinformatics#16]
If the taxon predicted by gambit is "None", the merlin workflow attempts to assign the variable "snippy_variants_none" a value of "". The workflow fails because this string cannot be coerced to a File output.

Error:
"Failed to evaluate 'merlin_magic.snippy_variants_results' (reason 1 of 1): Evaluating select_first([snippy_cauris.snippy_variants_results, snippy_calbicans.snippy_variants_results, snippy_afumigatus.snippy_variants_results, snippy_crypto.snippy_variants_results, snippy_variants_none]) failed: Cannot coerce the empty String value "" into a File."

[e69b1342-14b4-4bfd-b156-0c88d3501170](https://console.cloud.google.com/storage/browser/fc-1162d2b8-109d-42a8-b1b0-c05141aa98ad/submissions/e69b1342-14b4-4bfd-b156-0c88d3501170?authuser=michelle.scribner@theiagen.com)

**Comment by sage-wright** [comment]
Closed via #18
