### ISSUE TITLE
[TheiaProk] Update MLST for TheiaProk_ONT

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bioinformatics#172]
From Emma:

For some datasets, seems to be poor for calling MLST with Torsten's MLST tool with some data? May depend on input data quality and therefore quality of assembly. Could we try NanoMLST or krocus which are specifically intended for Nanopore reads?

**Comment by kapsakcj** [comment]
https://github.com/andrewjpage/krocus

It would be nice to add krocus. I don't have extensive experience with it, but I would consider adding this one. The downside is maintenance - looks like it has not been updated in 2 years.

Not so sure about NanoMLST, their documentation looks a bit sparse
