### ISSUE TITLE
[bug] case insensitivity in Mercury_Prep_N_Batch

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#186]
:bug:

I have only seen this bug once, so it is quite rare, but I wanted to document since it was sort of difficult to troubleshoot. Not a high priority to fix, but worth documenting.

### :pencil: Describe the Issue

It seems that the Mercury_Prep_N_Batch workflow, specifically the `sm_metadata_wrangling` task, does not parse the metadata columns with case sensitivity.

I ran into an issue where a user had both `Author` and `author` columns present in their Terra data table, but only the lowercase `authors` column had information filled out. The uppercase `Author` column was blank for their batch of samples.

When the workflow was run on these samples, it failed due to missing metadata since the capital `Authors` column was parsed instead of the lowercase column.

⚠️ It was also quite difficult to troubleshoot because the workflow did not finish gracefully & thus I could not see the `<output>_excluded_samples.tsv` file to see what went wrong/what metadata was missing. I had to run the workflow with `miniwdl` in order to see the excluded_samples.tsv file and it was not simple to run locally 😓 

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
Terra on GCP
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
no
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

Failed Terra workflow: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/4cfc0b9b-394a-4608-a693-417cc795840a
Successful Terra workflow after adding the correct metadata to both uppercase `Authors` and lowercase `authors` columns: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/ff2d6ead-9fdd-4d6b-92d6-d35a970c9146

### :fishing_pole_and_fish: Expected Behavior

parse the columns with case-sensitivity

### :floppy_disk: Version Information

v1.1.0

**Comment by sage-wright** [comment]
This one is tricky and I'm not sure that there is a good way to fix this, since in this line I'm converting everything to lowercase to avoid any issues with case -- this assumes that only one version of the column is present, which isn't the case here. https://github.com/theiagen/public_health_bioinformatics/blob/7f90b68a2fdaf57aaee97bf3676fdeaf2d67e2db/tasks/utilities/submission/task_mercury_file_wrangling.wdl#L120
I'm not sure how to fix this at the moment. Happy to hear any ideas. 

I do hear you about the excluded samples file. For some reason, Terra likes to delete the file if the workflow fails which is not good. I might `cat` the file so at least it appears in the log.

**Comment by sage-wright** [comment]
Trying this fix here: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/d4bf9588-679c-46b0-a6b8-ee8000d3060c

**Comment by kapsakcj** [comment]
> I do hear you about the excluded samples file. For some reason, Terra likes to delete the file if the workflow fails which is not good. I might cat the file so at least it appears in the log.

Yes, please! It would make the log for failed runs so much more informative if we could see the contents of the `excluded_samples.tsv` file!

Totally understand about the case-sensitivity part, it's super rare so I don't think it's a huge priority to catch that kind of edge case.

**Comment by kapsakcj** [comment]
Hit this issue again today with `Library_Id` (wrong) vs. `library_id` (correct). Just want to document it since it's rare but showing up with a teeny bit more frequency.
