### ISSUE TITLE
Genome Size Estimation - Ways to improve 

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#203]
Currently we have `kmc` as our genome size estimator on TheiaProk suite of workflows. This has shown to be widely inconsistent on ONT data, particularly when very long read sequences are present in the input files 

There are several ways we can improve this step. Here's a few options:

1. **Hyperparameter tunning of `kmc` k-mer length depending on the sequencing instrument.** According to @frankambrosio3, lowering the k-mer length (e.g. 9) has been showing more accurate results for genome size estimation. An alternative is to lower this value for the TheiaProk_ONT task. An important note is that this parameter is not exposed on the workflow level, so it cannot be adjusted by the user. 
2. **Jellyfish has been shown to be useful to estimate genome sizes, particularly for long-read sequencing data.** A tutorial on how to accomplish this is available at https://bioinformatics.uconn.edu/genome-size-estimation-tutorial/ 
3. **Implement and validate the new https://github.com/theiagen/gambitsizer developed by @andrewjpage.** Uses k-mers to estimate number of genes, which is then used to extrapolate genome size (assumes gene length of 1000 bp).

**Comment by michellescribner** [comment]
Noting that kmc limitations have also been detected for TheiaEuk

**Comment by sage-wright** [comment]
Potential solution: wrap task in a timer that will kill the task after X amount of hours to prevent excessive runtime

**Comment by sage-wright** [comment]
Recommendations:

If data volume > 1 GB, either:
- downsample data before analysis _or_
- provide a genome size

** May also want to implement the removal of `-sm` to prevent KMC stalling

**Comment by cimendes** [comment]
Duplicated by #301

**Comment by cimendes** [comment]
Duplicated by #301

**Comment by cimendes** [comment]
Re-opening the issue as KMC keeps being a struggle! Example with data from @emmadoughty:
- KMC is estimating 0 unique k-mers on a sample with over 1Gb of data
  - ![image](https://github.com/user-attachments/assets/0ebe8707-02c8-47bb-a925-e6d58e623d50)
- The https://github.com/theiagen/public_health_bioinformatics/pull/459 PR didn't actually address the issue of KMC over-estimating genome sizes, but it's just masking it from the user by setting an upper ceiling! 

@andrewjpage suggests we get rid of KMC all together from ONT workflows. As an alternative we can explore [Jellyfish](https://github.com/gmarcais/Jellyfish) or just pass a reasonable expected size (5Mb?).

The biggest impact is going to be on downsampling as newer versions of the assembler don't require an expected genome size. For [Flye](https://github.com/mikolmogorov/Flye/) genome size is no longer required since https://github.com/mikolmogorov/Flye/releases/tag/2.8-1 (latest version Flye 2.9.4, current implemented version through [dragonflye](https://github.com/rpetit3/dragonflye) 2.9.1-b1780).

**Comment by andrewjpage** [comment]
Identify a mean/median size for bacterial genomes, and set this as the expected size.
