### ISSUE TITLE
Errors with optional Augur_PHB inputs

### ISSUE THREAD

**Issue by kevinlibuit** [theiagen/public_health_bioinformatics#211]
:bug:

### :pencil: Describe the Issue

Users have reported issues with with optional Augur_PHB inputs, specifically `colors_tsv`. 

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP 

### :fishing_pole_and_fish: Expected Behavior

Error out of Augur_PHB: 
- Error_1:"Failed to evaluate 'colors_tsv' (reason 1 of 1): Evaluating select_first([colors, mpxv_defaults.colors]) failed: select_first was called with 2 empty values. We needed at least one to be filled."
- Error_2: "Failed to evaluate 'genes' (reason 1 of 1): Evaluating select_first([genes, mpxv_defaults.genes]) failed: select_first was called with 2 empty values. We needed at least one to be filled."

### :floppy_disk: Version Information

v1.2.0

### :information_source: Additional Information

Observed by multiple users

**Comment by kapsakcj** [comment]
Looks like this is related to @jrotieno 's recent PR: https://github.com/theiagen/public_health_bioinformatics/pull/160

One of the users mentioned that the workflow ran successfully with v1.1.0 but failed when they upgraded to v1.2.0

**Comment by jrotieno** [comment]
> Looks like this is related to @jrotieno 's recent PR: #160
> 
> One of the users mentioned that the workflow ran successfully with v1.1.0 but failed when they upgraded to v1.2.0

Separate and should be fixed by https://github.com/theiagen/public_health_bioinformatics/pull/212
