### ISSUE TITLE
nextclade_lineage output blank - theiacov wfs

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#215]
:bug:

### :pencil: Describe the Issue

It appears that the `nextclade_lineage` output of the TheiaCov workflows in not being properly parsed in the `nextclade_output_parser` task.

I am not sure when nextclade outputs changed, but I imagine this has been occuring for a while (few months?). If I recall correctly, nextclade outputs can change when the `nextclade_dataset_tag` is changed. (in addition to the possibility of them changing when nextclade versions change, which isn't very often anymore)

Maybe not the most critical issue to get a pango lineage out of `nextclade`, but still may be useful to users to see what lineage is assigned based on `nextclade` analysis

These lines needs to be updated: https://github.com/theiagen/public_health_bioinformatics/blob/7fdcf2bc3adc6758bc98c83c23724cb38b94a467/tasks/taxon_id/task_nextclade.wdl#L143-L144

### :repeat: How to Reproduce

I used nextclade 2.14.0 with dataset tag `2023-09-21T12:00:00Z` for sars-cov-2 samples with the TheiaCov_Illumina_PE workflow. workflow here: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/06e57076-a0c7-4114-8d53-4f436359b33e

- Was this run on the Terra platform?
  - Terra on GCP or Azure? GCP
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### :fishing_pole_and_fish: Expected Behavior

I expected the output for `nextclade_lineage` to be `BA.2` for the first sample in the workflow linked above

**Comment by sage-wright** [comment]
I think this is intended behavior. The `nextclade_lineage` field was created for mpox, not SC2, which is why it's blank for those samples. This is confusing though, because you would anticipate the column being filled for SC2 samples as well.

**Comment by kapsakcj** [comment]
closed via PR #239
