### ISSUE TITLE
[TheiaCoV] QC_Check task fails due to expecting int type on VADR num alerts

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#243]
:bug:

### :pencil: Describe the Issue

From @emily-smith1 

> We are seeing failures at the qc_check in TheiaCov whenever VADR is skipped which is causing the whole workflow to fail. Not urgent, but might be something worth fixing for the next patch release 

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

**Comment by kapsakcj** [comment]
Example STDOUT/STDERR:
```
File "<stdin>", line 329
qc_note, qc_status = compare(qc_note, "vadr_num_alerts", int(VADR skipped due to poor assembly; assembly length (unambiguous) = 1406), "<=", int(taxon_df["vadr_num_alerts"][0]))
^
SyntaxError: invalid syntax
```
From one of failed samples here: https://app.terra.bio/#workspaces/theiagen-training-workspaces/APHL_PRY_A_Rojas%20copy/job_history/0b7788e8-7806-4772-acbe-e62b997593a4

**Comment by kapsakcj** [comment]
re-posting Emma's message from duplicate issue #248 

> How to reproduce? Run TheiaCoV with QC_check using very poor quality assembly such that VADR cannot be run. See: https://app.terra.bio/#workspaces/theiagen-training-workspaces/APHL_PRY_demo/job_history/562fc5e8-2ee9-4eec-8df2-91f9d4151772 The TheiaProk workflow should also be checked for this error.

> Expected behavior? TheiaCoV workflow would run successfully, outputting results to the data table, even for very poor-quality assemblies, regardless of QC_check task being run
