### ISSUE TITLE
[SerotypeFinder] are we accurately comparing these?

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bioinformatics#254]
❓ 

### :pencil: Describe the Issue

In SerotypeFinder, we get serotypes such as the following:

O31/O136:H1
and
O136/O31:H1

We have been assuming these are identical. **_Are they?!_**

**Comment by kapsakcj** [comment]
I think they are the same serotype, and this occurs due to the ordering of the contigs. But it would be good to double check the actual blast hits & serotypefinder TSVs between these 2 results just to confirm
