### ISSUE TITLE
[AMRFinderPlus] Update database to latest version by next release

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#263]
:cool:

### :pushpin: Explain the Request

From LA county PHL "I think the AMRFinderPlus database was recently updated- might this also be included in the next release?"

Latest release of AMRFinderPlus: https://github.com/ncbi/amr/releases/tag/amrfinder_v3.11.26

From Curtis: "FYI the most up-to-date docker image (database included within) is this: "us-docker.pkg.dev/general-theiagen/staphb/ncbi-amrfinderplus:3.11.26-2023-11-15.1""

**Comment by kapsakcj** [comment]
OK if I close this duplicate issue in favor of: #129 ?
