### ISSUE TITLE
Make Plasmidfinder optional, on by default

### ISSUE THREAD

**Issue by michellescribner** [theiagen/public_health_bioinformatics#280]
:bug:

A collaborator reported repeated TheiaProk failures for Enterococcus samples at the plasmidfinder task: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/6d7a5682-0e30-44b7-8d66-8b9eac45bbf0

Cause of the issue is not clear to me. The same assembly run through the PlasmidFinder webtool successfully finished and detected plasmids but took several days to run. 

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

**Comment by kapsakcj** [comment]
Never seen this before. Looks like an issue with plasmidfinder code itself. Here's the relevant error:
```python
Traceback (most recent call last):
File "/plasmidfinder/plasmidfinder.py", line 360, in <module>
min_cov, threshold, method_path, cut_off=False)
File "/usr/local/lib/python3.5/dist-packages/cgecore/blaster/blaster.py", line 242, in __init__
hit)
File "/usr/local/lib/python3.5/dist-packages/cgecore/blaster/blaster.py", line 508, in calculate_new_length
new_start = int(gene_results[split]['sbjct_start'])
KeyError: 'contig00053 len=17204 cov=50.7 corr=0 origname=Contig_45_50.6781_pilon sw=shovill-skesa/1.1.0 date=20231218:7898..8044:rep1_9_repE(pKL0018)_AB290882:9.456740'
No plasmids detected in database
```

Perhaps you could try switching to `spades` as the assembly algorithm? FASTA headers will be different, so maybe that will help? 🤷

**Comment by michellescribner** [comment]
Good call, I just gave that a whirl: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/7a0e8786-bb73-4874-94ac-017acdaea0f3

I was thinking that the plasmidfinder web tool would fail if it was a fasta header issue but I'm not sure if the web tool is using the same exact software/db as our implementation

**Comment by kapsakcj** [comment]
FYI I think it's safe to assume that the version of plasmidfinder on the webtool is more recent than the one used in our docker image.

If this is an old bug that has already been addressed in the plasmidfinder code, then it would be a good idea to update the docker image to the most recent version and subsequently update the WDL to use the new one.

**Comment by michellescribner** [comment]
In the absence of a more recent version of plasmidfinder, in the meantime we can add a boolean to TheiaProk to turn off plasmidfinder. 

For example:
`call_plasmidfinder` = true
