### ISSUE TITLE
[feature request] add new output columns for Freyja QC values 

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#287]
:cool:

### :pushpin: Explain the Request

A user requested that the Freyja QC values (such as coverage) are outputted to the Terra data table instead of being only available in the output file.

### :books: Context

Requested by DE lab (so far)

### :chart_with_upwards_trend: Desired Behavior

Add necessary output column(s) to Freyja workflow

### :information_source: Additional Information

will edit this Issue with more info as I learn more

**Comment by emmadoughty** [comment]
Plan:

1. Identify Freyja QC outputs to add
3. Amend task_freyja_one-sample.wdl command block to capture values from the output file in the data table; add to the outputs section of the task file
4. Test?
5. Amend wf_freyja_fastq.wdl to add new QC outputs in the  wf outputs section
6. Test!
