### ISSUE TITLE
Adding flu and RSV to TheiaCoV fastq workflows (VADR)

### ISSUE THREAD

**Issue by kevinlibuit** [theiagen/public_health_bioinformatics#295]
:cool:

### :pushpin: Explain the Request

Update the TheiaCoV fastq workflows (e.g. Illumina PE/SE, ONT, etc) to add VADR to influenza and RSV organism tracks, similar to [TheiaCoV_FASTA](https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/theiacov/wf_theiacov_fasta.wdl#L96)

### :books: Context

Will help laboratories perform QC of additional viral assemblies generated

### :chart_with_upwards_trend: Desired Behavior

VADR outputs produced for more viral pathogens

**Comment by kevinlibuit** [comment]
**Note**: Flu will need to be added to all TheiaCoV workflows

**Comment by cimendes** [comment]
Flu and RSV models are available in the latest version of VADR (https://github.com/ncbi/vadr/wiki/Available-VADR-model-files)
Docker container available from [staph-b](https://github.com/StaPH-B/docker-builds/tree/master/vadr/1.6.3) at `us-docker.pkg.dev/general-theiagen/staphb/vadr:1.6.3` 

Commands to use:

**FLU**
`-r --atgonly --xnocomp --nomisc --alt_fail extrant5,extrant3 --mkey flu`

**RSV**
`-r  -xnocomp -mkey rsv`

⚠️ **WARNING:** RSV Model uses **over 30 GB** of memory according to https://github.com/StaPH-B/docker-builds/blob/master/vadr/1.6.3/Dockerfile#L176-L177

We should be cautious when proceeding with RSV.  Do we need to create two separate models for A and B to decrease the resource requirements?

**Comment by cimendes** [comment]
Solution: Pass the VADR memory requirement as input through the organism params sub-workflow
