### ISSUE TITLE
[feature request] automatically convert spaces to dashes in workflows that accept strings

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#326]
:cool:

### :pushpin: Explain the Request

It would save us all a bunch of time if our workflows like Augur_Prep, kSNP3, and others that accept input strings (like `build_name` for Augur_prep) are tolerant to spaces in them.

When users provide strings with spaces in them, e.g. `my augur build` , then the workflow fails due to the output files not being recognized by cromwell.

This will save us and our users much time in troubleshooting failed workflows due to pesky spaces.

A simple `sed` line to replace spaces with dashes `-` or underscores `_` on the respective variable should do the trick. Likely will go at the top of some command blocks in various WDL tasks.

Off the top of my head I would like to address these workflows, though there may be more:

- Augur_prep_phb
- Augur_phb (not sure on the direct impact on these two. may only have to change the augur_prep_phb workflow)
- kSNP3_PHB

**Comment by kapsakcj** [comment]
Other String inputs that I think could benefit from this change:

- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/freyja/wf_freyja_dashboard.wdl#L12
- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/freyja/wf_freyja_plot.wdl#L11
- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_core_gene_snp.wdl#L14
- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_find_shared_variants.wdl#L14
- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_lyveset.wdl#L11
- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_mashtree_fasta.wdl#L11
- https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_snippy_streamline.wdl#L16
- and probably more...

**Comment by AndrewLangvt** [comment]
@kapsakcj here's all of the ones I was able to find. When you have a moment, would you mind selecting which ones you think truly need this fix? My gut is it's everything in the first section and (maybe) a subset of the second. Obviously, all of the corresponding tasks are where the work would actually need to happen, but these should serve as reasonable "entry points" to identify the workflows needing attention. 
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/freyja/wf_freyja_dashboard.wdl#L12
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/freyja/wf_freyja_plot.wdl#L11
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_augur.wdl#L24
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_core_gene_snp.wdl#L14
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_find_shared_variants.wdl#L14
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_ksnp3.wdl#L14
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_lyveset.wdl#L11
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_mashtree_fasta.wdl#L11
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_snippy_streamline.wdl#L16
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_snippy_tree.wdl#L19
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/phylogenetics/wf_usher.wdl#L12
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/standalone_modules/wf_nullarbor.wdl#L10
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/submission/wf_mercury_prep_n_batch.wdl#L13
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/utilities/file_handling/wf_concatenate_column.wdl#L9
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/utilities/file_handling/wf_rename_fastq_files.wdl#L10
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/utilities/file_handling/wf_zip_column.wdl#L9

The below seem less likely candidates, but adding them here for review regardless: 
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/freyja/wf_freyja_update.wdl#L8
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/theiaprok/wf_theiaprok_fasta.wdl#L46
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/theiaprok/wf_theiaprok_illumina_pe.wdl#L64
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/theiaprok/wf_theiaprok_illumina_se.wdl#L63
- [ ] https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/theiaprok/wf_theiaprok_ont.wdl#L59

**Comment by kapsakcj** [comment]
Nullarbor likely not necessary to update. I don't believe we support that workflow anymore

**Comment by kapsakcj** [comment]
You can skip all those in the 2nd/less-likely list. Those need to be a specific syntax & known before running the workflow in order for them to work properly. 

GSURIs will never ever have spaces so they should fail if there's a typo.

`expected_taxon` in the context of NCBI amrfinderplus must be strings from this list here https://github.com/ncbi/amr/wiki/Running-AMRFinderPlus#--organism-option , so it should fail if there are spaces in the string. They HAVE to match for example `Acinetobacter_baumannii`

`expected_taxon` is also used to trigger organism-specific tasks in the merlin_magic subworkflow, so they will have to match the strings in the conditionals here: https://github.com/theiagen/public_health_bioinformatics/blob/64401efb8b4bd6f2cf4832e9d431354f9b88e12b/workflows/utilities/wf_merlin_magic.wdl#L92

**Comment by AndrewLangvt** [comment]
Ok, thanks much. So, now we're looking at 16 workflows in total that need modification. Thanks for the input here @kapsakcj

**Comment by AndrewLangvt** [comment]
Tested all workflows via miniwdl check and also ran through terra with the below results. All passing. 

- Freyja dashboard: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/7f7fdb9a-9777-46cc-a0b1-bdde0c06cb14
- Freyja plot: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/6291431a-f657-414b-abad-2799a1008677
- Augur_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/b42878a7-61fd-43c0-b248-e51f9aa675a3
- Find_Shared_Variants_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/4f0276b8-3e8e-4c7a-9fbd-2cafa0bcb7a0
- Lyve_SET_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/0e4d27d3-c3cd-474d-b9ff-c73b4d516783
- MashTree_FASTA_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/a0519b5e-9034-4d7b-9d09-2723ba0dcf2b
- Snippy_Streamline_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/9872d130-5df4-46a0-a8ad-d59f4bba0540
- Snippy_Tree_PHB (ran as sub-workflow of Snippy_Streamline_PHB)
- Usher_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/bc4a5b64-f1d0-441d-a2e1-bc9380cad2d6
- Mercury_Prep_N_Batch_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/51cdff4a-b902-4ce4-be29-3a843d765fe8
- Concatenate_Column_Content_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/8cb22e65-fdcd-4ad4-99a6-0adeac8a2b0e
- Rename_FASTQ_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/86562056-9842-4d62-a3cc-1c8506b7089a
- Zip_Column_Content_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/7b40a876-0f67-4691-93bc-c7ab8296c0dc
