### ISSUE TITLE
Set phred to 33 on trimmomatic task

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#332]
:cool:

Avoiding heartache and keyboard smashing on why trimmomatic is setting everything to the wrong phred encoding!

**Comment by kapsakcj** [comment]
agreed. Here's how I always run theiaprok_illumina_PE to avoid these trimmomatic errors. Should apply to TheiaCov workflows as well:
![image](https://github.com/theiagen/public_health_bioinformatics/assets/8172086/5fa645d2-4293-48d3-8982-8db6cf89fba7)


The exact string is `"-phred33"`

I think this could be a task-level default as it should be applied everywhere. As opposed to a workflow-level default (for example in the read_QC_trim subworkflows
