### ISSUE TITLE
[BUSCO] Update to latest release - v5.6.1

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#345]
:cool:

### :pushpin: Explain the Request
https://busco.ezlab.org/

https://gitlab.com/ezlab/busco/-/releases#5.6.1

**Comment by kapsakcj** [comment]
there is a staphb docker image available: https://github.com/StaPH-B/docker-builds/tree/master/busco/5.6.1

https://hub.docker.com/r/staphb/busco/tags

**Comment by kapsakcj** [comment]
ended up going with the docker image directly from the authors of BUSCO as it is more up-to-date than StaPH-B's docker image
