### ISSUE TITLE
[Snippy_Streamline] Add Snippy_variants QC outputs

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bioinformatics#353]
:cool:

### :pushpin: Explain the Request

Output the Snippy_Variants QC metrics in Snippy_Streamline

### :books: Context

The QC metrics in Snippy_Variants (https://github.com/theiagen/public_health_bioinformatics/pull/291) would be very helpful in Snippy_Streamline to determine if all samples should be included in the phylogenetic tree, or if the alignment is poor quality.

### :chart_with_upwards_trend: Desired Behavior

Output the Snippy_Variants QC metrics in Snippy_Streamline, either in the Terra table as a list of results and sample names printed next to them for each QC metric, or as a CSV/TSV file to download that contains a table of all QC results, if that is possible!

**Comment by jrotieno** [comment]
Add these metrics:
- snippy_variants_num_reads_aligned
- Proportion of reads aligned
- snippy_variants_num_variants
- snippy_variants_coverage_tsv
- snippy_variants_percent_ref_coverage
