### ISSUE TITLE
`cpu` is no longer a variable in the SRA_Fetch task

### ISSUE THREAD

**Issue by watronfire** [theiagen/public_health_bioinformatics#362]
The most recent commit (0c011eda8911b7e8f034fe58c5762f9bf83f2722) broke the SRA_Fetch workflow because it removed the tilde and curly braces surrounding `cpu`.

https://github.com/theiagen/public_health_bioinformatics/blame/0c011eda8911b7e8f034fe58c5762f9bf83f2722/tasks/utilities/data_import/task_sra_fetch.wdl#L29

**Comment by kapsakcj** [comment]
Thank you for the heads up, we will get this fixed soon! For now I would recommend using the v1.3.0 release of the workflow to avoid this issue.

**Comment by kapsakcj** [comment]
I just made a quick code change to address this issue. You can also use the branch called `cjk-sra-fetch-bugfix` which was created off of the `main` branch just now so it's more up-to-date with the code on `main`

I'm testing in Terra now, but 99.99% confident it will resolve the error

**Comment by kapsakcj** [comment]
@watronfire the bug has been resolved, the `main` branch for the SRA_fetch_PHB workflow is now functional again.

Thank you for reporting this bug! and thank you @sage-wright for the quick review 👍
