### ISSUE TITLE
[TheiaProk] Update MLST database

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#373]
:cool:

### :pushpin: Explain the Request

Update https://github.com/tseemann/mlst with latest version of mlst database https://pubmlst.org/
Target date: 25th March

**Comment by kapsakcj** [comment]
Now available on [dockerhub](https://hub.docker.com/r/staphb/mlst/tags)

`staphb/mlst:2.23.0-2024-03` 

TODOs

- [ ] push the image to our artifact registry and 
- [ ] submit a small PR to update the default docker image
