### ISSUE TITLE
[TheiaCoV] IRMA task runs out of disk space due to default TMP directory

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#412]
:bug:

### :pencil: Describe the Issue

I started dev branch `cjk-irma-diskcheck` to resolve this. It creates an IRMA configuration file, and sets the TMP directory used by IRMA to the PWD instead of the default `/tmp/root/` directory which is severely limited in space (something crazy low like 64MB) from cromwell's docker volume mounting.

PWD has access to the disk requested by the task (100GB default) so IRMA does not fail with large FASTQ files (300MB or larger)

If we see more IRMA failures due to large FASTQ files, downsampling the FASTQs prior to running TheiaCoV will usually fix this kind of error that we've seen sporadically:

```
[2024-04-11 18:37:59] IRMA/FLU started run '<samplename>'
[2024-04-11 18:37:59] IRMA/FLU ERROR: needed ~18425.78M to execute, but only 6064.29M available on disk
[2024-04-11 18:37:59] IRMA/FLU ABORTED run: <samplename>
```

Here's the output when using the dev branch which sets the TMP directory appropriately Expect to see this message:

```
[2024-04-11 21:17:49] IRMA/FLU started run '<samplename>'
[2024-04-11 21:17:49] IRMA/FLU found 97.2G free space, only needed ~18425.8M
[2024-04-11 21:23:46] IRMA/FLU pre-processed
```

We should also upgrade to the latest version of IRMA, which is 1.1.4 at the moment, but there may be another version on the horizon. Need to check CDCgov's dockerhub repo for IRMA to see

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

**Comment by sage-wright** [comment]
Also worth refactoring IRMA task as well
