### ISSUE TITLE
[TheiaProk] Add emmtyper tool to GAS TheiaProk track 

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#413]
:cool:

### :pushpin: Explain the Request

https://github.com/MDU-PHL/emmtyper

BLAST-based, uses assemblies

**Comment by sam-baird** [comment]
Hi, I'd like to work on a pull request for this if someone is not already working on it. When running a 32-sample validation dataset through the [GAS_identification](https://github.com/neranjan007/GAS_identification/tree/main) workflow, I noticed a couple discrepancies between the emm-typing-tool results and emmtyper results, so I think it would be nice if TheiaProk ran both tools. My plan would be to basically take the [emmtyper task](https://github.com/neranjan007/GAS_identification/blob/main/tasks/task_emmtyper.wdl) from GAS_identification and add the script to `tasks/species_typing/streptococcus/`, then call the task in `wf_merlin_magic.wdl` immediately below `if (merlin_tag == "Streptococcus pyogenes")`.

**Comment by kapsakcj** [comment]
We would ❤️ that. No one is actively working on this.

BTW we already have a WDL task file at `tasks/species_typing/streptococcus/task_emmtyper.wdl`, it's just not used in any workflows.

Though I'll note that Neranjan's WDL does have some additional code to parse out the final emm type, so probably best to use his copy as a starting point

**Comment by sam-baird** [comment]
Sounds good, thanks!
