### ISSUE TITLE
[Mercury] add flu

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bioinformatics#432]
:cool:

**Comment by emily-smith1** [comment]
Several job failures for different reasons in [this workspace](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/dataAnalysis_SARS-CoV-2_CDPH_Master_clone_2021-08-24/job_history)

**Comment by emily-smith1** [comment]
Successful job using the `smw-mercury-dev` branch in [this workspace](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/dataAnalysis_VRDL/job_history) resulting in successful submission of SC2 sequence data to GISAID, SRA, & GenBank.
