### ISSUE TITLE
[theiacov] update default pangolin docker image to pdata 1.27 & other default docker images when applicable

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#454]
:cool:

### :pushpin: Explain the Request

update default to `us-docker.pkg.dev/general-theiagen/staphb/pangolin:4.3.1-pdata-1.27`

here: https://github.com/theiagen/public_health_bioinformatics/blob/ecd98a99160d016e10bc6d5222c8348f60b08262/workflows/utilities/wf_organism_parameters.wdl#L46

**Comment by kapsakcj** [comment]
Should be completed before next release. Not urgent to update now

**Comment by sage-wright** [comment]
Also update other default docker images and dataset tags, etc. before next release if applicable
