### ISSUE TITLE
[Augur] Set sample_metadata_tsvs input in Augur_PHB to optional

### ISSUE THREAD

**Issue by emily-smith1** [theiagen/public_health_bioinformatics#458]
:cool:

### :pushpin: Explain the Request

Change the Augur_PHB input `sample_metadata_tsvs` from required to optional.

### :books: Context

Augur_PHB has an optional feature that allows users to output only a distance tree, which does not use any metadata. However, the sample_metadata_tsvs are still required inputs to the workflow, even if the users are only building a distance tree. This is a hinderance to users that just want a quick tree, without having to go through the time-consuming process of compiling metadata in the right format and running Augur_Prep_PHB.

### :chart_with_upwards_trend: Desired Behavior

The Augur_PHB input `sample_metadata_tsvs` is set to optional. This should not result in any functional changes to the workflow.

**Comment by jrotieno** [comment]
I am also going to the Augur_Prep_PHB inputs collection_date, country, state and continent optional. We can revert if we think otherwise of if we should set a default value.

**Comment by jrotieno** [comment]
One more thing. Whereas the issue addresses a need for a quick distance tree, we can evaluate later if we need to change the current logic get an auspice tree with AA mutations at the nodes, when metadata is not present.
