### ISSUE TITLE
Snippy_Variants: Calculate % reads aligned

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bioinformatics#477]
:cool:

### :pushpin: Explain the Request

Please add output for % reads aligned for Anippy_Variants

### :books: Context

Currently, Snipy_Variants provides an output column of # reads aligned, but this isn't put in context of the total number of reads in the sample. It would be very helpful to have a % calculated to be able to see if there are any major differences in the samples vs the ref, or any contamination indicated by low % reads aligned.

### :chart_with_upwards_trend: Desired Behavior

Add extra output column with %reads aligned

**Comment by jrotieno** [comment]
Looking at https://github.com/theiagen/public_health_bioinformatics/pull/592, I think we may have the numbers already available and only need to be calculated. For example, If I look at this new combined QC output:

samplename | reads_aligned_to_reference | variants_total | percent_ref_coverage | #rname | startpos | endpos | numreads | covbases | coverage | meandepth | meanbaseq | meanmapq | #rname | startpos | endpos | numreads | covbases | coverage | meandepth | meanbaseq | meanmapq
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ERR10913488 | 3504551 | 84125 | 84.5073 | AE003852 | 1 | 2961182 | 2376498 | 2615376 | 88.322 | 114.7 | 34.2 | 58.6 | AE003853 | 1 | 1072319 | 654185 | 830592 | 77.4575 | 87.0957 | 34.2 | 59

we can see that **3504551** were aligned to reference, whereas **2376498** and **654185** (total: **3030683**) were mapped to chromosomes 1 and 2, and **86.5%** of the reads.
