### ISSUE TITLE
[Release] Update amrfinderplus database for June 2024

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#511]

**Comment by kapsakcj** [comment]
https://hub.docker.com/r/staphb/ncbi-amrfinderplus/tags

latest docker image is: `staphb/ncbi-amrfinderplus:3.12.8-2024-05-02.2`

needs to be tested first; then if all is well can copy docker image to our GAR and update the default in the WDL

**Comment by kapsakcj** [comment]
Testing here on a variety of species with theiaprok_illumina_pe v2.0.1: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/bf89ba48-b226-4be6-8243-fbce50d9a3eb

🤞

**Comment by kapsakcj** [comment]
I want to note which organisms are not yet supported in our WDLs for organism-specific results from amrfinderplus.

Organisms available by the `amrfinder --organism` flag, but not yet implemented in WDL task/workflows (yet):

- `Enterobacter_asburiae`
- `Vibrio_parahaemolyticus`
- `Vibrio_vulnificus`

So basically what this means is that if these 3 species of bacteria are analyzed with TheiaProk (and this updated version of amrfinderplus v3.12.8; database v2024-05-02.2) then these samples will not have the `--organism` specific results and potentially miss some results

⚠️ P.S. I think there is supposed to be a space between the genus and species of `Enterococcusfaecium` on line 33 here. It depends on what string GAMBIT produces for this species:
https://github.com/theiagen/public_health_bioinformatics/blob/39cc380840ba1ebff2bce2cb9cb5a1f3e9ee5479/tasks/gene_typing/drug_resistance/task_amrfinderplus.wdl#L33

**Comment by kapsakcj** [comment]
I won't update this part of the code as part of this PR (should be done after the 2.1.0 release), but wanted to note for whomever tackles this dev task in the future
