### ISSUE TITLE
[TheiaCoV] Update kraken2 viral database to fix weird RSV-B nomenclature

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#520]
:bug:

### :pencil: Describe the Issue

Copied from #436 

> set 2 new default Strings for kraken_target_organism String rsv_a_kraken_target_organism = "Respiratory syncytial virus" and > String rsv_b_kraken_target_organism = "Human orthopneumovirus"
⚠️ NOTE: this was done due to the old kraken2 database used in this container us-docker.pkg.dev/general-theiagen/staphb/kraken2:2.0.8-beta_hv that is used in the kraken2_theiacov WDL task. We can revisit updating this task in the future. It’s pretty central to a lot of workflows so it would be a big change to update the database with up-to-date NCBI taxonomy IDs embedded within the kraken2 database. NCBI taxonomy has been updated so that Human orthopneumovirus is equivalent to human respiratory syncytial virus: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=11250&lvl=3&lin=f&keep=1&srchmode=1&unlock

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

**Comment by jrotieno** [comment]
I think we also need to consider updating `String? kraken_target_organism` as it is not the organism name but rather the proportion to `String? kraken_target_organism_prop`

**Comment by jrotieno** [comment]
I ran the standalone Kraken2_PE_PHB workflow here: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/74a5a714-c180-4baa-b8d0-c0b266c8dccc

I used the kraken database `"gs://theiagen-large-public-files-rp/terra/databases/kraken2/k2_standard_08gb_20240112.tar.gz"

Observing some interesting results:
RSV-A reads are preferentially classified under the species `Orthopneumovirus hominis` and sub-species S1 `Human orthopneumovirus` whereas RSV-B reads are prefenetially classified under the species `Orthopneumovirus bovis` and sub-species S1 `Bovine orthopneumovirus` and S2 `Respiratory syncytial virus`

**Comment by jrotieno** [comment]
Pending discussions on whether to update the docker image that includes an embedded database, or have the docker image separate from the database
