### ISSUE TITLE
[feature request] for Flu samples with no AA_dels or subs; output None instead of NA

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#523]
:cool:

### :pushpin: Explain the Request

A user requested that for Flu nextclade outputs for AA subs and dels, instead of outputting `NA` when nothing is found, write `None`.

"NA" is easily confused with the abbreviation for Neuraminidase.

Example:
![image (6)](https://github.com/theiagen/public_health_bioinformatics/assets/8172086/471d9856-1a2d-44a6-8f73-44ed3bafa7c1)

### :books: Context

FYI this will likely impact all other organisms that nextclade is run on, so it would be a somewhat broad change to the output format. With an impactful change like this, let's consider what the downstream impacts are, try to mitigate them, and warn users about the change in future versions

I believe this bit of code adds `NA` to the output string:
https://github.com/theiagen/public_health_bioinformatics/blob/d0377e139855252e15b57d7699aa6f5abb510996/tasks/taxon_id/task_nextclade.wdl#L179

### :chart_with_upwards_trend: Desired Behavior

Output `None` instead of `NA`

**Comment by sage-wright** [comment]
Can be addressed by training
