### ISSUE TITLE
maximum disk space limitation for snippy_core

### ISSUE THREAD

**Issue by abbymanson** [theiagen/public_health_bioinformatics#54]
It looks like the maximum disk space for snippy_core is 100G, but we need more than that!  Is it possible to add an option to increase the maximum disk space?

**Comment by kapsakcj** [comment]
Yes, thanks for raising the issue.

We've just exposed `disk_size` and `memory` optional inputs for the snippy_core task which is now accessible in the "Snippy_tree" workflow as well as the new workflow "Snippy_Streamline"

We've made the changes on the branch called `smw-snippy-enchilada-dev` and will be merging this into `main` once we've wrapped up testing and development

Just FYI this branch is still under active developement and will change without warning!

**Comment by sage-wright** [comment]
Closed with release of v1.0.0
