### ISSUE TITLE
Move fastq_scan and download_terra_table tasks to use GAR instead of Quay

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bioinformatics#571]
:cool:

### :pushpin: Explain the Request

fastq_scan uses quay.io 
download_terra_table uses quay.io

Resolve!!!

**Comment by kapsakcj** [comment]
huh, odd timing. I'm seeing some errors in Terra on the fastq-scan tasks when running the theiacov_illumina_pe workflow:
`Execution failed: generic::failed_precondition: pulling image: docker pull: running ["docker" "pull" "quay.io/biocontainers/fastq-scan@sha256:492b15cc462261422bd9e226964ab3bd0a0b1ac012f7ff88dd803b0ce68a7e1f"]: exit status 1 (standard error: "Error response from daemon: manifest for quay.io/biocontainers/fastq-scan@sha256:492b15cc462261422bd9e226964ab3bd0a0b1ac012f7ff88dd803b0ce68a7e1f not found: manifest unknown: manifest unknown\n")"`

Would be worth upgrading the fastq-scan version to v1.0.1 (latest version) and copy a docker image to our GAR
