### ISSUE TITLE
[wf_read_QC_trim_ont] Only run tiptoft if workflow_series is theiaprok

### ISSUE THREAD

**Issue by cimendes** [theiagen/public_health_bioinformatics#579]
:bug:

### :pencil: Describe the Issue

Right now tiptoft is run for every sample regardless of what workflow series is being passed to this sub-workflow. 
This task, which is one of the most expensive ones to run, should only be activated of series is TheiaProk.

https://github.com/theiagen/public_health_bioinformatics/blob/main/workflows/utilities/wf_read_QC_trim_ont.wdl#L112-L116

**Comment by sage-wright** [comment]
This task only runs if the workflow series is TheiaProk
