### ISSUE TITLE
Incorrect MLST scheme used for some Vibrio cholerae 

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bioinformatics#58]
_Vibrio cholerae_ has two MLST schemes, one for O1 or O139 serogroups, and one for non-O1/non-O139 serogroups. The latter is always being used regardless of serogroup. This needs to be amended

**Comment by cimendes** [comment]
@kevinlibuit This issue is a bit more relevant now given the interest in V. cholerae! Should we discuss it on the next dev sync?

**Comment by kapsakcj** [comment]
I agree we should update the workflow to accommodate, but I want to note the current workaround for this:

For O1 & O139 serogroup V. cholerae samples, the user can enter the string `"vcholerae_2"` in the optional input field called `scheme` for the `ts_mlst` task

`mlst` defaults to using `vcholerae` scheme
