### ISSUE TITLE
[TheiaProk] Update Bakta assembler to most recent version

### ISSUE THREAD

**Issue by fraser-combe** [theiagen/public_health_bioinformatics#606]
:cool:

### :pushpin: Explain the Request

The current version of Bakta being used in the workflow is v1.5.1. The latest stable release is version 1.9.4. This update will allow for improved accuracy, performance, and access to newly added features and bug fixes introduced in the newer versions.

**Comment by kapsakcj** [comment]
Hey Fraser, FYI this is a duplicate issue of #445 so I'm going to close it. But totally agree with you!
