### ISSUE TITLE
[TheiaProk] add concatenate across lanes functionality

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bioinformatics#621]
:cool:

### :pushpin: Explain the Request

enable ability to concatenate multiple lanes and then run theiaprok in a single workflow

**Comment by kapsakcj** [comment]
FYI I wrote a workflow for concatenating illumina reads a while back, it was never moved over to PHB. https://github.com/theiagen/terra_utilities/blob/cjk-concatenate-illumina/workflows/wf_concatenate_illumina.wdl

**Comment by kapsakcj** [comment]
great! just make sure you were aware since they are likely the only user of it 😆
