### ISSUE TITLE
[theiaprok docs] links to PHBG instead of PHB

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bioinformatics#624]
:bug:

### :pencil: Describe the Issue

I just found some docs that are linking to PHBG instead of PHB WDL code. These need to be updated. One example:

https://github.com/theiagen/public_health_bioinformatics/blob/9a10de708d97bbe5a5cbcce80c8e1ef5509f3f24/docs/workflows/genomic_characterization/theiaprok.md?plain=1#L686

**Comment by kapsakcj** [comment]
There's some more examples if you search for `public_health_bacterial_genomics` in this repo: https://github.com/search?q=repo%3Atheiagen%2Fpublic_health_bioinformatics%20public_health_bacterial_genomics&type=code

**Comment by kapsakcj** [comment]
and here's one reference to PHVG: https://github.com/search?q=repo%3Atheiagen%2Fpublic_health_bioinformatics%20public_health_viral_genomics&type=code

**Comment by sage-wright** [comment]
this is horrific and should be fixed please forgive me for i have sinned

**Comment by kapsakcj** [comment]
hahah it's no big deal 😆
