### ISSUE TITLE
[TheiaCoV] Reorder flu assembly segments in largest-to-smallest order

### ISSUE THREAD

**Issue by emily-smith1** [theiagen/public_health_bioinformatics#630]
:cool:

### :pushpin: Explain the Request

Re-ordering of the flu segments in the assembly_fasta file output by TheiaCoV in largest to smallest order: PB1, PB2, PA, HA, NP, NA, MP, NS, in accordance with Nextstrain/UShER formatting.

**Comment by Michal-Babins** [comment]
Is the expectations here to sort the segments and overwrite the file in place of the assembly fasta OR to save the ordered output to a modified file (ordered_assembly.fasta)?

**Comment by emily-smith1** [comment]
I'd suggest overwriting the existing assembly_fasta file to cut down on the number of output columns, unless the existing order is necessary for something downstream.

**Comment by Michal-Babins** [comment]
Did some testing against my [branch](https://github.com/theiagen/public_health_bioinformatics/tree/mb-reorder-flu-assembly-dev) and was able to confirm the assembly fasta correctly represents the ordered segments (PB2,PB1,PA,HA,NP,NA,MP,NS) after running end to end. 

Job history relating to this run can be found [here](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/42b14b65-0b37-4e4c-8127-154d256140a4), showing 10 successful runs.

You can check all the assemblies in the [flu_testing](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/data) data table to confirm the assemblies look as expected.
