### ISSUE TITLE
[Transfer_Column_Content] Workflow fails silently when permissions issues encountered

### ISSUE THREAD

**Issue by emily-smith1** [theiagen/public_health_bioinformatics#642]
:bug:

### :pencil: Describe the Issue

The workflow passes when files are unable to be transferred due to permissions issues. Users are running into errors when submitting reads to NCBI, as they are expecting read files to be in the bucket since the workflow passed, but NCBI can't find them.

**Comment by emily-smith1** [comment]
![Image](https://github.com/user-attachments/assets/87525430-7103-4d3f-94b6-fd4abc00a666)

**Comment by sage-wright** [comment]
could address this with set -euo pipefail. I might go ahead and make a PR that does this for a whole bunch of tasks
