### ISSUE TITLE
Update Freyja docker image to include --pathogen flag

### ISSUE THREAD

**Issue by michellescribner** [theiagen/public_health_bioinformatics#655]
:cool:

### :pushpin: Explain the Request

Freyja v1.5.2 introduces a --pathogen flag that allows you to indicate the pathogen being analyzed after the flag rather than providing barcode files. This will be helpful for groups analyzing non-SC2 wastewater samples. 

Thank you @cimendes for sharing this update!

**Comment by kapsakcj** [comment]
someone requested this over in staphb/docker-builds: https://github.com/StaPH-B/docker-builds/issues/1081

I'm not aware of anyone working on updating the dockerfile but it should be relatively easy to update staphb's freyja dockerfile
