### ISSUE TITLE
Nextclade update for Flu & SC2

### ISSUE THREAD

**Issue by AndrewLangvt** [theiagen/public_health_bioinformatics#669]
:cool: 
### :pushpin: Explain the Request
Nextclade datasets currently used in TheiaCoV defaults are outdated. Update to use the most-recent datasets for Flu & SC2 analyses. It looks to be that we are current for the remaining pathogens supported by TheiaCoV, but please review [current releases of nexclade dataset](https://github.com/nextstrain/nextclade_data/releases) vs. what we have implemented in PHB

**Comment by kapsakcj** [comment]
as of today 2024-11-19 the most current dataset tag for sars-cov-2 is: [2024-11-14--17-22-16Z](https://github.com/nextstrain/nextclade_data/releases/tag/2024-11-14--17-22-16Z)

`2024-11-14--17-22-16Z`

**Comment by kapsakcj** [comment]
andddddd it's out-of-date literally 9 minutes after I posted this 🤣 https://github.com/nextstrain/nextclade_data/releases/tag/2024-11-19--14-18-53Z

`2024-11-19--14-18-53Z` is now current for sars-cov-2

**Comment by kapsakcj** [comment]
pangolin docker image default update can be included with the PR that addresses updating nextclade_dataset_tag's

Latest docker image is `us-docker.pkg.dev/general-theiagen/staphb/pangolin:4.3.1-pdata-1.31` and has been tested to run successfully via theiacov_fasta on the `main` branch. I tested this today
