### ISSUE TITLE
LyveSET read files require unique identifiers before underscores

### ISSUE THREAD

**Issue by michellescribner** [theiagen/public_health_bioinformatics#95]

**Comment by michellescribner** [comment]
LyveSET wf fails if the read file names contain any underscores before uniquely identifying information because the shuffleSplitReads.pl script in lyveSET interleaves reads by combining read files by whatever is before the first underscore in the read file name. https://github.com/lskatz/lyve-SET/blob/master/scripts/shuffleSplitReads.pl

Potential solutions: 
- combine `sed` and `mv` to rename file names to avoid underscores except for before "_R"
- change the wf to take in sample names and use the sample name to rename files

**Comment by kapsakcj** [comment]
When I altered the filenames to have `_R1_001.fastq.gz` endings, the script ran without error.

I see there is a option `shuffleSplitReads.pl --regex`, perhaps we can use that in the workflow?

I'm surprised that files ending in `_R1.fastq.gz` & `_R2.fastq.gz` are not accepted
